// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWto0TelcA3xG7PsDCuFGP3UDV_BR5tY0',
    appId: '1:186416318404:web:f74336d597028eb368c691',
    messagingSenderId: '186416318404',
    projectId: 'first-auth-5c1ac',
    authDomain: 'first-auth-5c1ac.firebaseapp.com',
    storageBucket: 'first-auth-5c1ac.firebasestorage.app',
    measurementId: 'G-MN2ZTMHWJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4blnck2sdR2fFKUhT9BJ2PmyiV-YvmbM',
    appId: '1:186416318404:android:572641bb6a7d48af68c691',
    messagingSenderId: '186416318404',
    projectId: 'first-auth-5c1ac',
    storageBucket: 'first-auth-5c1ac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI9bxfj5In42HJxLaOblyFeDd7NqXHLK4',
    appId: '1:186416318404:ios:33da1f3b215fe9e568c691',
    messagingSenderId: '186416318404',
    projectId: 'first-auth-5c1ac',
    storageBucket: 'first-auth-5c1ac.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI9bxfj5In42HJxLaOblyFeDd7NqXHLK4',
    appId: '1:186416318404:ios:33da1f3b215fe9e568c691',
    messagingSenderId: '186416318404',
    projectId: 'first-auth-5c1ac',
    storageBucket: 'first-auth-5c1ac.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWto0TelcA3xG7PsDCuFGP3UDV_BR5tY0',
    appId: '1:186416318404:web:2b121a6f12da92bd68c691',
    messagingSenderId: '186416318404',
    projectId: 'first-auth-5c1ac',
    authDomain: 'first-auth-5c1ac.firebaseapp.com',
    storageBucket: 'first-auth-5c1ac.firebasestorage.app',
    measurementId: 'G-0VPK79CVMP',
  );
}
